import Head from "next/head";
import Image from "next/image";

const slugs = ["/", "/foo", "/foo/bar"];

const Page = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>
        Welcome to <a href="https://nextjs.org">Next.js!</a>
      </h1>
    </div>
  );
};

export default Page;

const slugToArray = (slug) => {
  if (slug === "/") return [""];
  return slug?.split("/")?.filter((x) => {
    if (!x) return false;
    if (x === "") return false;
    return true;
  });
};

export const getStaticPaths = async () => {
  const paths = slugs?.map((slug) => {
    const slugArray = slugToArray(slug);
    return {
      params: {
        slug: slugArray,
      },
    };
  });

  return {
    paths,
    fallback: "blocking",
  };
};

export const getStaticProps = async (context) => {
  const { preview } = context;
  const { slug: slugArray } = context.params;
  const slug = slugArray ? `/${slugArray?.join("/")}` : "/";

  const notFound = !slugs.includes(slug);

  const props = {
    slug,
    preview: preview || null,
  };

  return {
    props,
    revalidate: 10,
    notFound,
  };
};
